spring.datasource:
  url: jdbc:mysql://localhost:3306/poleposition
  username: app
  password: password

harvester:
  maxRetries: 3
  minWaitBetweenRequestsInSecs: 30
  maxWaitBetweenRequestsInMins: 5