spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poleposition
    username: app
    password: password
  jackson:
    serializationInclusion: NON_EMPTY
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

harvester:
  maxRetries: 3
  minWaitBetweenRequestsInSecs: 30
  maxWaitBetweenRequestsInMins: 5
